### ISSUE TITLE
Can orders be fulfilled with arbitrary logic? 

### ISSUE THREAD

**Issue by James-Sangalli** [0xProject/protocol#193]
Hi All,

I have this question here on reddit: https://www.reddit.com/r/0xProject/comments/mkf0g7/is_0x_capable_of_handling_conditional_and_multi/

Will be building a protocol that requires that orders contain such special logic and we desire to build the marketplace system on 0x. Please let me know if such arbitrary logic works with 0x as is, because I am still unsure based even after reading the documentation.

**Comment by ptrwtts** [comment]
Hey James. I'm just a fellow doc browser, but could this be done with Extensions?

https://0x.org/docs/guides/0x-extensions-explained

Or if you need something more bare metal, maybe the Wyvern Protocol could work (what Open Sea runs on currently)?

https://wyvernprotocol.com/docs
