### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by MahmutYamann** [0xProject/protocol#393]
404 Not Found on https://github.com/0xProject/fast-abi/releases/download/0.0.2/node-v93-darwin-x64.tar.gz

**Comment by abls** [comment]
This is likely the same problem as #352

**Comment by elenadimitrova** [comment]
There has been an update to the installation instructions and additionally the asset-swapper package has been removed from this repo. Closing this now but please reopen if installation is still a problem.
