### ISSUE TITLE
0x OrderBook API

### ISSUE THREAD

**Issue by nassirian** [0xProject/protocol#511]
Hi,
i have a question,
getting lists of orders from API sometimes there are some orders that partially filled. so the remainingFillableTakerAmount is not match with takerAmount. 
so in this case i know how much takerAmount remain to fill the order but how can i get remaining makerAmount?

here is the sample 
{
  order: {
    signature: {
      signatureType: 2,
      r: '0xaea5ba688652d721d217e0f1ab497ffb374a1d12957b3f7e530792779d4ed5d7',
      s: '0x76678e4e4a6c68123d188aee67f06ab6b1fa45c121e275ec0fe62f503f875011',
      v: 27
    },
    sender: '0x0000000000000000000000000000000000000000',
    maker: '0xffc2ac30f4de505f35040db3cb94d2b657c4d62a',
    taker: '0x0000000000000000000000000000000000000000',
    takerTokenFeeAmount: '0',
    makerAmount: '500000000000000',
    takerAmount: '1655000000',
    makerToken: '0x34f0915a5f15a66eba86f6a58be1a471fb7836a7',
    takerToken: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
    salt: '1656080555',
    verifyingContract: '0xdef1c0ded9bec7f1a1670819833240f027b25eff',
    feeRecipient: '0x86003b044f70dac0abc80ac8957305b6370893ed',
    expiry: '1656685355',
    chainId: 1,
    pool: '0x0000000000000000000000000000000000000000000000000000000000000000'
  },
  metaData: {
    orderHash: '0xfd6b0fad03c48e3b3d73695ee525bfca0e785f1bada515d7a5e07df522ee0c1c',
    remainingFillableTakerAmount: '12051369',
    createdAt: '2022-06-24T14:22:37.277Z'
  }
}

**Comment by abls** [comment]
The ratio of remaining fillable takerToken to the total takerToken is the same as the ratio of the remaining fillable makerToken to the total makerToken.

Basically, you just calculate a fractional amount of total makerToken based on the takerToken ratio and floor the result:

`floor((remainingFillableTakerAmount / takerAmount) * makerAmount) = remainingFillableMakerAmount`

Or in your specific case:

`floor((12051369 / 1655000000) * 500000000000000) = 3640896978851`

You can see an example of this [here](https://github.com/0xProject/protocol/blob/2aadbda527c56df9b3fbc9d023915955c507477f/contracts/zero-ex/contracts/src/features/native_orders/NativeOrdersInfo.sol#L375).

**Comment by abls** [comment]
The ratio of remaining fillable takerToken to the total takerToken is the same as the ratio of the remaining fillable makerToken to the total makerToken.

Basically, you just calculate a fractional amount of total makerToken based on the takerToken ratio and floor the result:

`floor((remainingFillableTakerAmount / takerAmount) * makerAmount) = remainingFillableMakerAmount`

If you are doing it in solidity or in js with some BigNumber library that cuts off decimal places, you will want to do it like this:

`remainingFillableTakerAmount * makerAmount / takerAmount = remainingFillableMakerAmount`

You can see an example of that [here](https://github.com/0xProject/protocol/blob/2aadbda527c56df9b3fbc9d023915955c507477f/contracts/zero-ex/contracts/src/features/native_orders/NativeOrdersInfo.sol#L375).

And to answer your specific case:

`floor((12051369 / 1655000000) * 500000000000000)  = 3640896978851`

**Comment by nassirian** [comment]
@abls thanks make sense
